### ISSUE TITLE
Галерея

### ISSUE THREAD

**Issue by jonkofee** [cherja/dymchenko-art#3]
Оживить галерею с фотографиями с помощью плагина https://feimosi.github.io/baguetteBox.js используя `FadeIn animation`

**Comment by JonKofee** [comment]
test

**Comment by jonkofee** [comment]
Вот документацию по нему https://github.com/feimosi/baguetteBox.js

**Comment by jonkofee** [comment]
- [x] При наведении на картинку в галереи - она должна становиться светлее

**Comment by jonkofee** [comment]
- [x] для элемента галлереи transition: 0.5s; opacity: .8;
